# Generated by Django 3.1.7 on 2021-03-13 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciat', models.CharField(max_length=100)),
                ('resposta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 3, 13, 11, 58, 7, 608648, tzinfo=utc))),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infcovid.resultat')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infcovid.pregunta')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infcovid.test')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('I', 'Informació'), ('RE', 'Restriccions'), ('MS', 'Mascaretes'), ('SI', 'Símptomes')], default='I', max_length=9)),
                ('resposta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infcovid.respostaconsulta')),
                ('usuari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
