# Generated by Django 3.1.7 on 2021-03-28 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('I', 'Informació'), ('RE', 'Restriccions'), ('MS', 'Mascaretes'), ('SI', 'Símptomes')], default='I', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciat', models.CharField(max_length=100)),
                ('resposta', models.CharField(choices=[('YES', 'Sí'), ('NO', 'No')], default='YES', max_length=9)),
                ('correcta', models.CharField(choices=[('YES', 'Sí'), ('NO', 'No')], default='YES', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultat', models.CharField(max_length=100)),
                ('pregunta', models.ManyToManyField(to='infcovid.Pregunta')),
            ],
        ),
    ]
