# Generated by Django 3.1.7 on 2021-03-20 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infcovid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='correcta',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No')], default='YES', max_length=9),
        ),
        migrations.AddField(
            model_name='test',
            name='auto_increment_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='test',
            name='pregunta',
            field=models.ManyToManyField(to='infcovid.Pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='resposta',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No')], default='YES', max_length=9),
        ),
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 11, 14, 37, 196832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='resultat',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PreguntaTest',
        ),
        migrations.DeleteModel(
            name='Resultat',
        ),
    ]
