# Generated by Django 3.1.7 on 2021-03-17 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infcovid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 17, 9, 11, 79707, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PreguntaTest',
        ),
    ]
