# Generated by Django 3.1.7 on 2021-03-12 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infcovid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infcovid.respostaconsulta'),
        ),
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 19, 9, 15, 55940, tzinfo=utc)),
        ),
    ]
