# Generated by Django 3.1.7 on 2021-03-28 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infcovid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consulta',
            name='resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infcovid.respostaconsulta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
