# Generated by Django 3.1.7 on 2021-03-12 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infcovid', '0002_auto_20210312_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 19, 10, 13, 680038, tzinfo=utc)),
        ),
    ]
