# Generated by Django 3.1.7 on 2021-03-17 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infcovid', '0002_auto_20210317_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Pregunta_1',
            field=models.ManyToManyField(to='infcovid.Pregunta'),
        ),
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 17, 11, 36, 914559, tzinfo=utc)),
        ),
    ]
