# Generated by Django 3.1.7 on 2021-03-20 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infcovid', '0002_auto_20210320_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 11, 26, 26, 188817, tzinfo=utc)),
        ),
    ]
