# Generated by Django 3.1.7 on 2021-03-17 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infcovid', '0003_auto_20210317_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Pregunta_1',
            new_name='Pregunta',
        ),
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 17, 14, 22, 27363, tzinfo=utc)),
        ),
    ]
