# Generated by Django 3.1.7 on 2021-03-17 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infcovid', '0004_auto_20210317_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='resposta',
            field=models.CharField(choices=[('YES', 'Sí'), ('NO', 'No')], default='YES', max_length=9),
        ),
        migrations.AlterField(
            model_name='test',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 17, 16, 39, 941780, tzinfo=utc)),
        ),
    ]
